[project]
src = "src"
dot_env = ".env"

[networks.anvil]
url = "http://127.0.0.1:8545"
save_to_db = false
prompt_live = false
default_account_name = "Anvil1"
unsafe_password_file = "~/.moccasin/unsafe-passwords/Anvil1"

# [networks.anvil-zksync]
# url = "http://127.0.0.1:8011"
# save_to_db = false
# prompt_live = false
# default_account_name = "Anvil1"
# unsafe_password_file = "~/.moccasin/unsafe-passwords/Anvil1"
# is_zksync = true


[networks.sepolia]
url = "$RPC_URL"
save_to_db = false
prompt_live = false
default_account_name = "sepolia1"
explorer_uri = "https://eth-sepolia.blockscout.com/"
explorer_type = "blockscout"
unsafe_password_file = "~/.moccasin/unsafe-passwords/Sepolia1"

[networks.sepolia-tenderly]
url = "$tenderly_sepolia_RPC_URL"
chain_id = 111555111
save_to_db = false
prompt_live = false
default_account_name = "sepolia1"
# explorer_uri = "$tenderly_sepolia_block_explorer"
# explorer_type = "blockscout"
unsafe_password_file = "~/.moccasin/unsafe-passwords/Sepolia1"

[networks.sepolia-zksync]
url = "$zksync_sepolia_RPC_URL"
chain_id = 300
prompt_live = false
default_account_name = "sepolia1"
explorer_uri = "https://explorer.sepolia.era.zksync.dev"
explorer_type = "zksyncexplorer"
unsafe_password_file = "~/.moccasin/unsafe-passwords/Sepolia1"
is_zksync = true

# [networks.pyevm]
# is_zksync = false

# [networks.anvil-zksync]
# url = "http://127.0.0.1:8011"
# prompt_live = false
# save_to_db = false


# [networks.sepolia]
# url = "https://ethereum-sepolia-rpc.publicnode.com"
# chain_id = 11155111

# [networks.fakecoin]
# url = "https://virtual.sepolia.rpc.tenderly.co/d8376854-1b54-4d65-89b8-15c12cd1bd37"
# chain_id = 111555111

# [networks.zksync-sepolia]
# url = "https://sepolia.era.zksync.dev"
# chain_id = 300
# is_zksync = true
# prompt_live = true

# You can view all configuration options at https://cyfrin.github.io/moccasin/ all_moccasin_toml_parameters.html
